# Generated by Django 4.1 on 2022-08-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='user_sch',
            field=models.CharField(default='동의대학교', max_length=50),
        ),
    ]
