# Generated by Django 4.1 on 2022-08-19 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_user_sch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user_sch',
        ),
    ]
