# Generated by Django 4.1 on 2022-08-21 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_board'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
    ]
