# Generated by Django 4.1 on 2022-08-21 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='author',
            new_name='board_author',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='content',
            new_name='board_content',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='title',
            new_name='board_title',
        ),
    ]
