# Generated by Django 4.1 on 2022-08-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_rename_author_board_board_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_board_title', models.CharField(max_length=100)),
                ('s_board_content', models.CharField(max_length=500)),
                ('s_board_author', models.CharField(max_length=100)),
            ],
        ),
    ]
